### ISSUE TITLE
Feature Request: syslog plugin

### ISSUE THREAD

**Issue by elisboa** [aws-samples/amazon-eks-fluent-logging-examples#5]
I would like to be able to use the "syslog" type plugin. When I change the configmap, I get an error, saying this gem isn't installed. And, as the image runs with user "fluent", it can't install any gems.

I would like to have some instruction regarding making these changes. If I had access to the Dockerfile that created the image         carmenpuccio/fluentd-aws-elasticsearch-service I believe I could change it to my needs. So, any instructions would be very useful.

Thanks in advance.

**Comment by CarmenAPuccio** [comment]
My apologies @elisboa I never saw this issue. Here is a copy of what I did back then for the demo.

`FROM fluent/fluentd:v1.7-1

USER root

RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-aws-elasticsearch-service \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY conf/* /fluentd/etc/
COPY entrypoint.sh /bin/

ENV FLUENTD_CONF="stdout.conf"

ENV LD_PRELOAD=""
EXPOSE 24224 5140

USER fluent
ENTRYPOINT ["tini",  "--", "/bin/entrypoint.sh"]
CMD ["fluentd"]
`
